In [1]:
import sys
sys.path.append("..")

import torch
import numpy as np

In [ ]:
import gym
t_env = gym.make('PongNoFrameskip-v0')
t_env.observation_space.shape

In [2]:
from envs.wrapped_envs import make_vec_atari_envs, make_env_atari, make_vec_envs
from envs.benchmarking_envs.benchmarking_envs import make_atari_env

raw_env = make_atari_env('PongNoFrameskip-v0')
env = make_env_atari('PongNoFrameskip-v0', 1, 0, './results', True)()
envs = make_vec_atari_envs(
    'PongNoFrameskip-v0', 1, 1, 0.99, './results', torch.device('cpu'), True, norm_reward=True)
m_envs = make_vec_envs('MountainCar', 1, 1, 0.99, './results', torch.device('cpu'), True, norm_reward=True)

Box(0.0, 255.0, (64, 64, 12), float32)
Box(0.0, 255.0, (12, 64, 64), float32)
Box(0.0, 255.0, (64, 64, 12), float32)
Box(0.0, 255.0, (12, 64, 64), float32)
Box(0.0, 255.0, (64, 64, 12), float32)
Box(0.0, 255.0, (12, 64, 64), float32)


D:\Applications\Python\Miniconda3\envs\gluon\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [3]:
obs_r = env.reset()
obs_s = env.reset()
obs_m = envs.reset()
m_obs_m = m_envs.reset()

obs_r = torch.tensor(obs_r)
obs_s = torch.tensor(obs_s)
display(obs_r)
display(obs_s)
display(obs_m)
display(m_obs_m)

tensor([[[0.3922, 0.3922, 0.3922,  ..., 0.5647, 0.5647, 0.5647],
         [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
         [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
         ...,
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

        [[0.1961, 0.1961, 0.1961,  ..., 0.2824, 0.2824, 0.2824],
         [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
         [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
         ...,
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

        [[0.0471, 0.0471, 0.0471,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.

tensor([[[0.3922, 0.3922, 0.3922,  ..., 0.5647, 0.5647, 0.5647],
         [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
         [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
         ...,
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

        [[0.1961, 0.1961, 0.1961,  ..., 0.2824, 0.2824, 0.2824],
         [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
         [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
         ...,
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
         [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

        [[0.0471, 0.0471, 0.0471,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.

tensor([[[[0.3922, 0.3922, 0.3922,  ..., 0.5647, 0.5647, 0.5647],
          [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
          [0.5647, 0.5647, 0.5647,  ..., 0.5647, 0.5647, 0.5647],
          ...,
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

         [[0.1961, 0.1961, 0.1961,  ..., 0.2824, 0.2824, 0.2824],
          [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
          [0.2824, 0.2824, 0.2824,  ..., 0.2824, 0.2824, 0.2824],
          ...,
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255],
          [0.9255, 0.9255, 0.9255,  ..., 0.9255, 0.9255, 0.9255]],

         [[0.0471, 0.0471, 0.0471,  ..., 0.0667, 0.0667, 0.0667],
          [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
          [0.0667, 0.0667, 0.0667,  ..., 0

tensor([[-0.4711,  0.0000]])